# SOF west manifest
manifest:
  version: "0.13"

  defaults:
    remote: innersource

  remotes:
    - name: thesofproject
      url-base: https://github.com/thesofproject
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: innersource
      url-base: https://github.com/intel-innersource

  projects:
    - name: rimage
      repo-path: drivers.audio.firmware.rimage
      path: sof/rimage
      revision: 6b4848e25d8aaabdf6cd9d402db9a02e5c62ae56

    - name: tomlc99
      remote: thesofproject
      repo-path: tomlc99
      path: sof/rimage/tomlc99
      revision: e3a03f5ec7d8d33be705c5ce8a632d998ce9b4d1

    - name: zephyr
      repo-path: os.rtos.zephyr.zephyr
      path: zephyr
      revision: 0b6fd79b9fe7ca7ae105ff6d6780cda31d46b551
      import:
        name-whitelist:
          - hal_xtensa
          - mbedtls
          - mipi-sys-t
          - lz4
          - tinycrypt

    - name: zephyr-intel
      path: zephyr-intel
      repo-path: os.rtos.zephyr.zephyr-intel
      revision: 76a11dc00cdb10699b85cea9f373a95234293e4e

    - name: hal-intel
      repo-path: os.rtos.zephyr.modules.hal-intel
      path: modules/hal/intel
      revision: da7a7bc3d3ab108430f25465c84acff78a0c2195

  self:
    path: sof
    import: submanifests
